name: update-homebrew-formula-action
description: update a formula of Homebrew

inputs:
  path:
    description: glob path
    required: true
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
