name: update-homebrew-formula-action
description: Update a Homebrew formula to the desired version

inputs:
  path:
    description: Glob pattern to formula(s)
    required: true
  version:
    description: Desired version of the formula(s)
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
