name: ts

on:
  push:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.lock'
      - action.yaml
      - .github/workflows/ts.yaml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.lock'
      - action.yaml
      - .github/workflows/ts.yaml

jobs:
  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable pnpm
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm format-check
      - run: pnpm test
      - run: pnpm build

      - name: e2e-test
        uses: ./
        with:
          path: tests/fixtures/*.rb
      - run: git diff
